package com.revature.rnd;

public class Generator {
	//Generated Names
	public static String name[] = {
	    "Temeka Cornforth",
	    "Modesto Orme",
	    "Augustus Prisbrey",
	    "Tiffiny Hemmings",
	    "Argentina Cowher",
	    "Brigida Debruyn",
	    "Herman Begaye",
	    "Tania Crater",
	    "Karima Glandon",
	    "Marine Clem",
	    "Fernande Rost",
	    "Charlotte Joyal",
	    "Bobbye Fisk",
	    "Bernetta Ginsburg",
	    "Doyle Backhaus",
	    "Zenaida Drake",
	    "Shaquita Gathers",
	    "Exie Becerra",
	    "Rena Kober",
	    "Vanda Falk",
	    "Sidney Gonsalves",
	    "Stacee Gerhart",
	    "Duane Alongi",
	    "Shin Mcswain",
	    "Alayna Cambra",
	    "Marci Halpin",
	    "Pamelia Sandford",
	    "Belinda Tondreau",
	    "Camellia Massenburg",
	    "Frieda Summerford",
	    "Laurinda Gammill",
	    "Luann Auerbach",
	    "Wyatt Fleeman",
	    "Scarlett Charley",
	    "Myles Sharif",
	    "Cherilyn Mcivor",
	    "Janie Choi",
	    "Brain Rubino",
	    "Mamie Sjoberg",
	    "Magda Ogara",
	    "Iliana Bynum",
	    "Gina Pletcher",
	    "Nedra Osburn",
	    "Britt Modisette",
	    "Rona Koger",
	    "Latarsha Odem",
	    "Ernesto Kowaleski",
	    "Damaris Hock",
	    "Gena Maravilla",
	    "Mechelle Monzo",
	};
	
	
}
